### ISSUE TITLE
 An error occurred after running for a while: timeout

### ISSUE THREAD

**Issue by lilihongjava** [ideawu/c1000k#5]
Command:
./server 7000
./client 127.0.0.1 7000

When running to a certain time
error message：
....
connections: 129999, fd: 130001
connections: 130573
error: Connection timed out

**Comment by ideawu** [comment]
so conclusion is your server doesn't support c1000k.

**Comment by lilihongjava** [comment]
> so conclusion is your server doesn't support c1000k.

Maybe because of something? I want to tune  Linux kernel parameters  to meet the requirements of c1000k.

**Comment by lilihongjava** [comment]
Solve the problem after modifying net.nf_conntrack_max
